### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by eozturk1** [bitcoinjs/bip32-utils#15]
I recently started learning about HD wallets and found this library. I was wondering whether there was any documentation available on the API. 

Also, compared to the [BIP32 repo](https://github.com/bitcoinjs/bip32), does `bip32-utils` provide a low(er) level interface -- but the same interface in high-level?

**Comment by junderw** [comment]
This repo should not be used since it depends on an old version of bitcoinjs-lib.

**Comment by eozturk1** [comment]
What could an alternative HD wallet library in Javascript?

**Comment by junderw** [comment]
bip32 should be sufficient.

Is it too low level?

**Comment by eozturk1** [comment]
bip32-utils API seems more verbose which I would prefer. I will go with the bip32 then. Thank you @junderw!
