### ISSUE TITLE
There is a reference to bitcoin.hdNode in README but there is no such thing in bitcoinjs-lib 

### ISSUE THREAD

**Issue by Adoliin** [bitcoinjs/bip32-utils#16]
So is `hdNode` something that was used before but now removed from `bitcoinjs-lib`?
If so what can I do to replace it?

**Comment by junderw** [comment]
`bitcoinjs.bip32` or just `require('bip32')`

A pull request to fix the README would be appreciated.

**Comment by Adoliin** [comment]
> A pull request to fix the README would be appreciated.

Yes sure I just did one https://github.com/bitcoinjs/bip32-utils/pull/17
I fixed the first and second code blocks but didn't do anything to the third because it too is using an old library `cb-blockr` that I don't think this README should be using.

Also to test these changes of the README one must use the latest commit of this library and not the old version "0.11.1" one.
So I think we should release a new version of this library because when someone add this to their project via `npm` or `yarn` they get the old version (0.11.1) that is not compatible with the latest version of `bitcoinjs-lib`

**Comment by Adoliin** [comment]
Another thing do you need help refactoring this codebase to Typescript?

Or at least add type definition to it?

**Comment by junderw** [comment]
I have no plans on doing anything with this library, as I personally don't find it too useful and neither does anyone I work with/for.

If you can make a PR, I'll review it. Any changes that are too big should be discussed ahead of time before any large PRs are created.

The worst feeling is to work on a huge PR and get a concept NACK from the maintainer.

**Comment by junderw** [comment]
TS and/or definitions-only seems pretty straightforward though. I'm cool with it.

---

This issue is done. Closing.
