### ISSUE TITLE
Instantiate a BIP32 class from a private key?

### ISSUE THREAD

**Issue by ekkis** [bitcoinjs/bip32-utils#19]
the methods `.fromEntropy` and `.fromExtendedKey` allow instantiating a class from a BIP39 phrase or an extended private/public key, but how can I do it using the hex (ascii) representation of a private key alone?

**Comment by junderw** [comment]
Are you sure you have the right repository?

I think you are mistaken.

**Comment by ekkis** [comment]
I'm sorry.  the libraries between python (the language I'm using) and NodeJs are similarly named and I didn't realise I was here.  however, the same applies.  is there a way, do you  know? because this repo doesn't seem to offer that either
