### ISSUE TITLE
Rename to bip32

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bip32-utils#3]
This repository will implement most of the patterns that exist in the [official BIP](https://github.com/bitcoin/bips/blob/master/bip-0032mediawiki),   with https://github.com/bitcoinjs/bip32-wallet being the canonical wallet implementation _using_ these patterns.

Thoughts @jprichardson?
Ideally,  we'd also move `HDNode` from https://github.com/bitcoinjs/bitcoinjs-lib into this module too.

**Comment by jprichardson** [comment]
No, I don't think it should be renamed to `bip32`. I think `hdnode` should be extracted and renamed to `bip32`.

**Comment by dcousens** [comment]
@jprichardson is that just a matter of the primary export though?  I still feel like derivation utilities such as those that exist here (or intend to) should definitely be bundled with the core data structure.

**Comment by dcousens** [comment]
bump @jprichardson

**Comment by jprichardson** [comment]
> I still feel like derivation utilities such as those that exist here (or intend to) should definitely be bundled with the core data structure (that is HDNode)

Agreed with this.

But address discovery should be integrated with `bip32-wallet`, yes?

**Comment by dcousens** [comment]
> But address discovery should be integrated with bip32-wallet or stay in bip32-utils yes?

This I can't decide.  It is clearly mentioned in the BIP (see quote below).

> In cases where two systems need to access a single shared wallet, and both need to be able to perform spendings, one needs to share the master private extended key. Nodes can keep a pool of N look-ahead keys cached for external chains, to watch for incoming payments. The look-ahead for internal chains can be very small, as no gaps are to be expected here. An extra look-ahead could be active for the first unused account's chains - triggering the creation of a new account when used. Note that the name of the account will still need to be entered manually and cannot be synchronized via the block chain.

So I'm not sure where it should go,  it would feel odd being combined with the core datastructure, so maybe you are right that it should go to `bip32-wallet`.

**Comment by dcousens** [comment]
Related https://github.com/bitcoinjs/bip32-wallet/issues/6

**Comment by dcousens** [comment]
> But address discovery should be integrated with bip32-wallet or stay in bip32-utils yes?

What is provided is an algorithm that is agnostic of any network information,  so in that sense it is purely related to key management.
I think it would be OK for it to remain integrated.

Thoughts?

**Comment by dcousens** [comment]
Also related: https://github.com/bitcoin/bips/pull/293

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bip32/issues/1
