### ISSUE TITLE
possible to generate addresses from a master public key?

### ISSUE THREAD

**Issue by timbowhite** [bitcoinjs/bip32-utils#4]
Hi, just curious if this module can be used to generate an arbitrary # of addresses from an MPK?  The examples all seem to require the seed in hex format.

**Comment by dcousens** [comment]
@timbowhite I'm not sure what you're asking?

Perhaps it would be best for you to look at https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/hdnode.js.

You can use `HDNode.fromBase58` to initialize a `HDNode` from say `xpub661MyMwAqRbcFtXgS5sYJABqqG9YLmC4Q1Rdap9gSE8NqtwybGhePY2gZ29ESFjqJoCu1Rupje8YtGqsefD265TMg7usUDFdp6W1EGMcet8`,  and then perform the exact same operations as in the examples in this repositories README.

**Comment by timbowhite** [comment]
gotcha thanks!
